apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf
  namespace: argocd  # ✅ ArgoCD가 설치된 네임스페이스 (보통 'argocd')
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: deploykf  # ✅ deployKF가 배포될 네임스페이스
  source:
    repoURL: https://github.com/deployKF/deployKF
    path: deploykf
    targetRevision: main
    helm:
      valueFiles:
        - ../../my-values.yaml  # ✅ values 파일 경로 (아래 참고)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
