apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploykf
  namespace: argocd
spec:
  destination:
    namespace: deploykf
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jjdevhub/deployKF
    targetRevision: main
    path: manifests/generated/deploykf-app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
